name: binderNotebooks
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - matplotlib
  - plotly
  - sympy
  - pillow
  - pyyaml
  - nbformat
  - jsonschema
  - pandoc
  - jupytext
  - rise
  - pip:
      - dash
  - jupyter-dash
      - -e ./1DFEM
