name: fem
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter-book
  - jupyterlab
  - jupyterlab_rise
  - jupytext
  - matplotlib
  - numpy
  - pandas
  - sympy
  - rise
  - ipywidgets
  - plotly
  - dash
  - jupyter-dash
  - pip:
      - jupyterlab-rise-metadata-form
      - markdown
      - ./1DFEM
name: binderNotebooks
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - plotly
  - sympy
  - pillow
  - pyyaml
  - nbformat
  - jsonschema
  - pandoc
  - jupytext
  - rise
  - pip:
      - dash
  - jupyter-dash
      - -e ./1DFEM
